[package]
name = "openrusty-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
openrusty-core = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
tokio = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
socket2 = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rustls-pki-types = { workspace = true }
tokio-rustls = { workspace = true }
tower = { workspace = true }

[dev-dependencies]
