//! ConfigMap + TOML rendering behind `openrusty inject`: the second output
//! document and the sidecar's configuration file.
//!
//! The TOML is deliberately minimal and locked by tests: three listeners
//! (transparent inbound/outbound + admin), `[egress]` per the annotations,
//! plugins pointed at a missing dir, ingress off, and - when the
//! `app-port` annotation is set - a pod-local `app` upstream
//! (`127.0.0.1:<port>`) with a catch-all route. It must load through
//! `openrusty_core::load_config` - the render function validates its own
//! output before the command ever prints it.

use super::render::to_value;
use super::{
    InjectParams, ADMIN_PORT, INBOUND_PORT, MANAGED_BY, MANAGED_BY_LABEL, OUTBOUND_PORT,
    PLUGINS_DIR, PREFIX, SUBCOMMAND,
};
use openrusty_core::config::{validate, Config, EgressMode};
use serde::Serialize;
use serde_yaml::Value;
use std::collections::BTreeMap;

/// ConfigMap data key holding the sidecar config.
pub const CONFIG_KEY: &str = "openrusty.toml";

/// The second output document: `<name>-openrusty-config` with the sidecar
/// TOML under [`CONFIG_KEY`].
pub fn render_config_map(
    name: &str,
    namespace: Option<String>,
    p: &InjectParams,
) -> Result<Value, String> {
    #[derive(Serialize)]
    struct Metadata {
        name: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        namespace: Option<String>,
        labels: BTreeMap<&'static str, String>,
    }
    #[derive(Serialize)]
    struct ConfigMap {
        #[serde(rename = "apiVersion")]
        api_version: &'static str,
        kind: &'static str,
        metadata: Metadata,
        data: BTreeMap<String, String>,
    }
    let cm = ConfigMap {
        api_version: "v1",
        kind: "ConfigMap",
        metadata: Metadata {
            name: format!("{name}-openrusty-config"),
            namespace,
            labels: BTreeMap::from([(MANAGED_BY_LABEL, MANAGED_BY.to_string())]),
        },
        data: BTreeMap::from([(
            CONFIG_KEY.to_string(),
            render_config_toml(p)?,
        )]),
    };
    to_value(&cm)
}

/// The minimal sidecar TOML, self-validated before it is handed out.
pub fn render_config_toml(p: &InjectParams) -> Result<String, String> {
    if p.egress_mode == EgressMode::Gateway && p.egress_gateway.is_empty() {
        return Err(format!(
            "egress-mode \"gateway\" requires the {PREFIX}egress-gateway annotation"
        ));
    }
    let gateway_line = if p.egress_mode == EgressMode::Gateway {
        format!("gateway = \"{}\"\n", p.egress_gateway)
    } else {
        String::new()
    };
    // Pod-local app upstream (v1: single port): transparently intercepted
    // inbound HTTP otherwise hits the router with no route and 404s - an
    // injected pod could never serve its app. `127.0.0.1` needs no DNS.
    let app_section = match p.app_port {
        Some(port) => format!(
            concat!(
                "\n[[upstreams]]\n",
                "name = \"app\"\n",
                "\n",
                "  [[upstreams.peers]]\n",
                "  addr = \"127.0.0.1:{port}\"\n",
                "\n",
                "[[routes]]\n",
                "path_prefix = \"/\"\n",
                "upstream = \"app\"\n",
                "\n",
            ),
            port = port,
        ),
        None => String::new(),
    };
    let src = format!(
        concat!(
            "# Generated by `openrusty inject`; edit with care - the sidecar\n",
            "# restarts with this file verbatim.\n",
            "[server]\n",
            "listen = \"0.0.0.0:{inbound}\"\n",
            "log_level = \"{log}\"\n",
            "\n",
            "[[server.listeners]]\n",
            "role = \"inbound\"\n",
            "listen = \"0.0.0.0:{inbound}\"\n",
            "transparent = true\n",
            "\n",
            "[[server.listeners]]\n",
            "role = \"outbound\"\n",
            "listen = \"0.0.0.0:{outbound}\"\n",
            "transparent = true\n",
            "\n",
            "[[server.listeners]]\n",
            "role = \"admin\"\n",
            "listen = \"0.0.0.0:{admin}\"\n",
            "\n",
            "[plugins]\n",
            "# No plugins volume: a missing dir is \"no plugins\", never fatal.\n",
            "dir = \"{plugins}\"\n",
            "\n",
            "[egress]\n",
            "mode = \"{mode}\"\n",
            "{gateway_line}",
            "{app_section}",
            "[ingress]\n",
            "enabled = false\n",
        ),
        inbound = INBOUND_PORT,
        outbound = OUTBOUND_PORT,
        admin = ADMIN_PORT,
        log = p.log_level,
        plugins = PLUGINS_DIR,
        mode = egress_mode_str(p.egress_mode),
        gateway_line = gateway_line,
        app_section = app_section,
    );
    // Fail at inject time, not at sidecar boot: the rendered TOML must
    // parse and pass `validate`. The one tolerated failure is an
    // egress-gateway hostname that only resolves inside the cluster (the
    // sidecar re-validates at boot, where the name resolves).
    let cfg: Config = toml::from_str(&src).map_err(|e| format!("rendered config invalid: {e}"))?;
    match validate(&cfg) {
        Ok(()) => Ok(src),
        Err(e) if e.to_string().contains("egress.gateway must be a resolvable host:port") => {
            eprintln!(
                "openrusty {SUBCOMMAND}: warning: egress gateway {:?} does not resolve here \
                 (cluster-internal DNS?); the sidecar validates it at boot",
                p.egress_gateway
            );
            Ok(src)
        }
        Err(e) => Err(format!("rendered config invalid: {e}")),
    }
}

fn egress_mode_str(mode: EgressMode) -> &'static str {
    match mode {
        EgressMode::Direct => "direct",
        EgressMode::Gateway => "gateway",
        EgressMode::Deny => "deny",
    }
}
