#!/usr/bin/env bash
#
# install-service.sh - Install OpenRusty gateway + demo echo upstreams as
# systemd services that start now and on boot. Idempotent: safe to re-run;
# re-runs rewrite the unit files and restart all units so new binaries are
# picked up.
#
# Installs:
#   /etc/systemd/system/openrusty.service         (the gateway)
#   /etc/systemd/system/openrusty.socket          (socket activation)
#   /etc/systemd/system/openrusty-echo@.service   (template demo upstream)
#   enables+starts openrusty-echo@9001/9002/9003, openrusty.socket and
#   openrusty.service. systemd binds the listeners and hands the fds to the
#   gateway via LISTEN_FDS; without them the gateway binds the ports itself.
#
set -euo pipefail

REPO_DIR="/root/openrusty"
GATEWAY_BIN="$REPO_DIR/target/release/openrusty"
ECHO_BIN="$REPO_DIR/target/release/examples/echo_upstream"
CONFIG="$REPO_DIR/config/openrusty.toml"
ECHO_UNIT="/etc/systemd/system/openrusty-echo@.service"
GATEWAY_UNIT="/etc/systemd/system/openrusty.service"
SOCKET_UNIT="/etc/systemd/system/openrusty.socket"
ECHO_INSTANCES=(openrusty-echo@9001 openrusty-echo@9002 openrusty-echo@9003)
ECHO_UNITS=""
for u in "${ECHO_INSTANCES[@]}"; do ECHO_UNITS+="$u.service "; done
ECHO_UNITS="${ECHO_UNITS% }"

fail() { echo "ERROR: $*" >&2; exit 1; }

# Effective gateway listeners of a TOML config, in file order, deduped:
# the `listen` under [server] plus every `listen` inside
# [[server.listeners]] blocks. Commented lines and other tables are
# ignored. Prints one host:port value per line (stdout).
extract_listeners() {
  awk '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*\[/ {
      table = $0
      sub(/^[[:space:]]*\[\[?/, "", table)
      sub(/\]\]?[[:space:]]*(#.*)?$/, "", table)
      gsub(/[[:space:]]/, "", table)
      next
    }
    table != "server" && table != "server.listeners" { next }
    $0 !~ /^[[:space:]]*listen[[:space:]]*=/ { next }
    {
      val = $0
      sub(/^[[:space:]]*listen[[:space:]]*=[[:space:]]*/, "", val)
      quote = substr(val, 1, 1)
      if (quote != "\"" && quote != "\047") next
      val = substr(val, 2)
      end = index(val, quote)
      if (end < 2) next
      val = substr(val, 1, end - 1)
      if (val != "" && !seen[val]++) print val
    }
  ' "$1"
}

# --- 1. must run as root (systemd unit installation requires it) -----------
[[ $(id -u) -eq 0 ]] || fail "must run as root (try: sudo bash $0)"

# --- 2. release binaries must exist -----------------------------------------
missing=0
for bin in "$GATEWAY_BIN" "$ECHO_BIN"; do
  if [[ ! -x "$bin" ]]; then
    echo "missing binary: $bin" >&2
    missing=1
  fi
done
if [[ $missing -ne 0 ]]; then
  fail "release binaries not found. Build them first:
  cd $REPO_DIR
  cargo build --release -p openrusty-server
  cargo build --release -p openrusty-server --example echo_upstream"
fi
[[ -f "$CONFIG" ]] || fail "runtime config $CONFIG not found (copy config/openrusty.example.toml)"

# --- 3. write the echo upstream template unit -------------------------------
cat > "$ECHO_UNIT" << UNIT
# OpenRusty demo echo upstream (template). %i is the port / node id.
[Unit]
Description=OpenRusty demo echo upstream on port %i
After=network.target

[Service]
Type=simple
ExecStart=$ECHO_BIN 127.0.0.1:%i node%i
Restart=on-failure

[Install]
WantedBy=multi-user.target
UNIT
echo "wrote $ECHO_UNIT"

# --- 4. write the gateway unit ----------------------------------------------
cat > "$GATEWAY_UNIT" << UNIT
# OpenRusty gateway. WorkingDirectory is required: the config references
# the relative plugin dir "build/plugins".
[Unit]
Description=OpenRusty WASM plugin gateway
# systemd binds the listeners (openrusty.socket) and passes the fds via
# LISTEN_FDS; the gateway adopts them, or binds the ports itself if absent.
Requires=openrusty.socket
After=network.target openrusty.socket $ECHO_UNITS
Wants=$ECHO_UNITS

[Service]
Type=simple
WorkingDirectory=$REPO_DIR
ExecStart=$GATEWAY_BIN $CONFIG
Restart=on-failure
LimitNOFILE=65535
# The ports are bound by systemd, not the gateway, so the gateway can run
# unprivileged once a dedicated user exists - uncomment to drop privileges:
# User=openrusty

[Install]
WantedBy=multi-user.target
UNIT
echo "wrote $GATEWAY_UNIT"

# --- 5. write the socket activation unit ------------------------------------
# One ListenStream per effective listener (extract_listeners), config order.
# Re-run this script whenever the listeners in $CONFIG change.
mapfile -t LISTENERS < <(extract_listeners "$CONFIG")
[[ ${#LISTENERS[@]} -gt 0 ]] || \
  fail "no listeners found in $CONFIG (expected listen = \"host:port\" under [server] or [[server.listeners]])"
{
  echo "# OpenRusty gateway socket activation (generated by install-service.sh)."
  echo "# Must stay in sync with the listen entries in $CONFIG."
  echo "[Socket]"
  for listener in "${LISTENERS[@]}"; do
    echo "ListenStream=$listener"
  done
  echo "Backlog=511"
  echo
  echo "[Install]"
  echo "WantedBy=sockets.target"
} > "$SOCKET_UNIT"
echo "wrote $SOCKET_UNIT (${#LISTENERS[@]} listener(s): ${LISTENERS[*]})"

# --- 6. reload systemd, enable and (re)start everything ---------------------
systemctl daemon-reload
systemctl enable openrusty.socket

for unit in "${ECHO_INSTANCES[@]}"; do
  systemctl enable "$unit.service"
  # restart (not start) so re-runs pick up freshly built binaries
  systemctl restart "$unit.service"
done
systemctl enable openrusty.service
# Safe order for re-runs: stop the gateway first (it may hold the ports
# itself when it started standalone), then let systemd (re)bind the
# listeners, then restart the gateway on the inherited fds.
systemctl stop openrusty.service || true
systemctl restart openrusty.socket
systemctl restart openrusty.service

# --- 7. report ---------------------------------------------------------------
echo
echo "unit status (is-enabled / is-active):"
report_units=()
for unit in "${ECHO_INSTANCES[@]}"; do report_units+=("$unit.service"); done
report_units+=(openrusty.socket openrusty.service)
for unit in "${report_units[@]}"; do
  enabled=$(systemctl is-enabled "$unit" 2>/dev/null || true)
  active=$(systemctl is-active "$unit" 2>/dev/null || true)
  printf '  %-28s %-10s %s\n' "$unit" "$enabled" "$active"
done

echo
echo "done. check logs with: journalctl -u openrusty -f"

# Only relevant for deployments that opt into server.log_file; the default
# unit logs to stdout, which journald rotates on its own.
if grep -q '^[[:space:]]*log_file[[:space:]]*=' "$CONFIG" 2>/dev/null; then
  echo
  echo "note: server.log_file is set - logs go to the file, not the journal."
  echo "rotate it with /etc/logrotate.d/openrusty (rename + SIGUSR1 reopen,"
  echo "no copytruncate), e.g.:"
  echo '  /var/log/openrusty/*.log {'
  echo '      daily'
  echo '      rotate 14'
  echo '      compress'
  echo '      missingok'
  echo '      notifempty'
  echo '      sharedscripts'
  echo '      postrotate'
  echo '          systemctl kill -s SIGUSR1 openrusty.service'
  echo '      endscript'
  echo '  }'
fi
